In [11]:
import octree
import numpy as np
from stl import mesh

In [11]:
box=[0,0,0,10,20,30]
print(octree.splitOctBoxes(box))

[[0, 0, 0, 5.0, 10.0, 15.0], [5.0, 0, 0, 10, 10.0, 15.0], [0, 10.0, 0, 5.0, 20, 15.0], [5.0, 10.0, 0, 10, 20, 15.0], [0, 0, 15.0, 5.0, 10.0, 30], [5.0, 0, 15.0, 10, 10.0, 30], [0, 10.0, 15.0, 5.0, 20, 30], [5.0, 10.0, 15.0, 10, 20, 30]]


In [12]:
tree = octree.Octree("cube.stl")

ValueError: operands could not be broadcast together with shapes (3,) (6,) 

In [36]:
stl_mesh = mesh.Mesh.from_file("cube.stl")

In [38]:
triangles = np.append(stl_mesh.points.reshape((-1,3,3)), stl_mesh.normals.reshape((-1,1,3)),axis=1)

In [39]:
triangles.shape

(12, 4, 3)

In [40]:
assert triangles.shape[1:]==(4,3)

In [24]:
stl_mesh.normals.shape

(12, 3)

In [25]:
stl_mesh.points.shape

(12, 9)

In [26]:
stl_mesh.normals.reshape((-1,1,3))

array([[[-10000.,      0.,     -0.]],

       [[-10000.,      0.,      0.]],

       [[     0., -10000.,      0.]],

       [[     0., -10000.,      0.]],

       [[ 10000.,      0.,      0.]],

       [[ 10000.,      0.,     -0.]],

       [[     0.,  10000.,      0.]],

       [[     0.,  10000.,      0.]],

       [[     0.,      0.,  10000.]],

       [[     0.,      0.,  10000.]],

       [[     0.,      0., -10000.]],

       [[     0.,      0., -10000.]]], dtype=float32)

In [27]:
stl_mesh.normals.reshape((-1,1,3)).shape

(12, 1, 3)

In [29]:
np.append(stl_mesh.points.reshape((-1,3,3)), stl_mesh.normals.reshape((-1,1,3)),axis=1)

array([[[     0.,    100.,    100.],
        [     0.,    100.,      0.],
        [     0.,      0.,      0.],
        [-10000.,      0.,     -0.]],

       [[     0.,      0.,      0.],
        [     0.,      0.,    100.],
        [     0.,    100.,    100.],
        [-10000.,      0.,      0.]],

       [[     0.,      0.,    100.],
        [     0.,      0.,      0.],
        [   100.,      0.,      0.],
        [     0., -10000.,      0.]],

       [[   100.,      0.,      0.],
        [   100.,      0.,    100.],
        [     0.,      0.,    100.],
        [     0., -10000.,      0.]],

       [[   100.,      0.,    100.],
        [   100.,      0.,      0.],
        [   100.,    100.,      0.],
        [ 10000.,      0.,      0.]],

       [[   100.,    100.,      0.],
        [   100.,    100.,    100.],
        [   100.,      0.,    100.],
        [ 10000.,      0.,     -0.]],

       [[   100.,    100.,    100.],
        [   100.,    100.,      0.],
        [     0.,    100.,

In [30]:
np.append(stl_mesh.points.reshape((-1,3,3)), stl_mesh.normals.reshape((-1,1,3)),axis=1).shape

(12, 4, 3)

In [31]:
a=np.ones((2,9))
b=np.zeros((2,3))

In [32]:
a

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [33]:
b

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [34]:
np.append(a.reshape((-1,3,3)), b.reshape((-1,1,3)),axis=1)

array([[[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 0.,  0.,  0.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 0.,  0.,  0.]]])

In [42]:
bounding_box = np.append(stl_mesh.min_, stl_mesh.max_)

In [1]:
from octree import *

tree = Octree("ball.stl")
boxes, bounding_box=tree.traverse()

Level 0, ctriangels:0, itriangles:79, box:[-49.96046829 -49.99011612 -50.          50.          49.99011612  50.        ]
Level 1, ctriangels:0, itriangles:79, box:[-49.960468, -49.990116, -50.0, 0.019765853881835938, 0.0, 0.0]
Level 1, ctriangels:0, itriangles:40, box:[0.019765853881835938, -49.990116, -50.0, 50.0, 0.0, 0.0]
Level 1, ctriangels:0, itriangles:79, box:[-49.960468, 0.0, -50.0, 0.019765853881835938, 49.990116, 0.0]
Level 1, ctriangels:0, itriangles:40, box:[0.019765853881835938, 0.0, -50.0, 50.0, 49.990116, 0.0]
Level 1, ctriangels:0, itriangles:79, box:[-49.960468, -49.990116, 0.0, 0.019765853881835938, 0.0, 50.0]
Level 1, ctriangels:0, itriangles:40, box:[0.019765853881835938, -49.990116, 0.0, 50.0, 0.0, 50.0]
Level 1, ctriangels:0, itriangles:79, box:[-49.960468, 0.0, 0.0, 0.019765853881835938, 49.990116, 50.0]
Level 1, ctriangels:0, itriangles:40, box:[0.019765853881835938, 0.0, 0.0, 50.0, 49.990116, 50.0]
Level 2, ctriangels:0, itriangles:79, box:[-24.970351219177246

In [2]:
len(boxes)

16

In [3]:
stl_mesh = mesh.Mesh.from_file("ball.stl")

In [4]:
stl_mesh.points.shape

(6162, 9)

In [5]:
stl_mesh = mesh.Mesh.from_file("step.stl")
stl_mesh.points.shape

(36, 9)

In [1]:
from octree import *
tree = Octree("step.stl")
boxes, bounding_box=tree.traverse()

Level 0, ctriangels:22, itriangles:14, box:[   0.    0.    0.  100.  100.  100.]
Level 1, ctriangels:12, itriangles:0, box:[0.0, 0.0, 0.0, 50.0, 50.0, 50.0]
Level 1, ctriangels:12, itriangles:0, box:[50.0, 0.0, 0.0, 100.0, 50.0, 50.0]
Level 1, ctriangels:12, itriangles:0, box:[0.0, 50.0, 0.0, 50.0, 100.0, 50.0]
Level 1, ctriangels:14, itriangles:0, box:[50.0, 50.0, 0.0, 100.0, 100.0, 50.0]
Level 1, ctriangels:12, itriangles:0, box:[0.0, 0.0, 50.0, 50.0, 50.0, 100.0]
Level 1, ctriangels:12, itriangles:4, box:[50.0, 0.0, 50.0, 100.0, 50.0, 100.0]
Level 1, ctriangels:14, itriangles:0, box:[0.0, 50.0, 50.0, 50.0, 100.0, 100.0]
Level 1, ctriangels:18, itriangles:6, box:[50.0, 50.0, 50.0, 100.0, 100.0, 100.0]
Level 2, ctriangels:4, itriangles:0, box:[50.0, 0.0, 50.0, 75.0, 25.0, 75.0]
Level 2, ctriangels:4, itriangles:0, box:[75.0, 0.0, 50.0, 100.0, 25.0, 75.0]
Level 2, ctriangels:4, itriangles:0, box:[50.0, 25.0, 50.0, 75.0, 50.0, 75.0]
Level 2, ctriangels:6, itriangles:0, box:[75.0, 25.0, 

In [2]:
len(boxes)

21